import { type NextPage } from "next";
import Head from "next/head";
import { BrandsSlider } from "../components/BrandsSlider";
import { Hero } from "../components/Hero";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>PlanetScale UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden">
        <Hero />

        <BrandsSlider />
      </main>
    </>
  );
};

export default Index;
